build: streamline macOS build via ssh

diff --git a/build/macos/Makefile b/build/macos/Makefile
--- a/build/macos/Makefile
+++ b/build/macos/Makefile
@@ -15,27 +15,11 @@ usage:
 	@echo "Hello, this is a Makefile for macOS build."
 	@echo ""
 	@echo "Type one of the following commands:"
-	@echo "  make suika.dmg ... build the main game engine"
-	@echo "  make release   ... build apps for a release"
-	@echo "  make cap-rep   ... build suika-capture.app and suika-replay.app"
-
-#
-# Build the main app only
-#
-suika.dmg: libroot
-	@echo "Building..."
-	@xcodebuild -scheme suika -project suika.xcodeproj -configuration Release -archivePath `pwd`/build/Release/suika.xcarchive archive
-	@echo "Uploading..."
-	@xcodebuild -exportArchive -archivePath `pwd`/build/Release/suika.xcarchive -exportOptionsPlist export-options.plist
-	@echo "Waiting for notarization..."
-	@rm -rf build/Release/suika.app
-	@until \
-		xcodebuild -exportNotarizedApp -archivePath `pwd`/build/Release/suika.xcarchive -exportPath `pwd`/build/Release; \
-	do \
-	    echo "Sleep..."; \
-	    sleep 10; \
-	done
-	@rm -rf tmp mac.dmg && mkdir tmp && cp -Rv build/Release/suika.app tmp/ && hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname suika-mac mac.dmg && codesign --sign $(SIGNATURE) mac.dmg && rm -rf tmp
+	@echo "  make main    ... build suika.app (the main game engine)"
+	@echo "  make pro     ... build suika-pro.app"
+	@echo "  make helpers ... build Kirara helpers"
+	@echo "  make capture ... build suika-capture.app"
+	@echo "  make replay  ... build suika-replay.app"
 
 #
 # This builds "libroot" directory.
@@ -44,21 +28,33 @@ libroot:
 	./build-libs.sh
 
 #
-# Build release apps
+# Build release main app
 #
-release: libroot
+main: libroot
 	@echo "Building..."
-	@rm -rf build mac.dmg mac-pro.dmg mac.zip pack.mac
 	@security unlock-keychain -p "$(MACOS_PASSWORD)" login.keychain
 	@echo "Builing suika.app" && xcodebuild -scheme suika -project suika.xcodeproj -configuration Release -archivePath `pwd`/build/Release/suika.xcarchive archive
 	@echo "Uploading suika.app" && xcodebuild -exportArchive -archivePath `pwd`/build/Release/suika.xcarchive -exportOptionsPlist export-options.plist
 	@echo "Notarizing suika.app" && rm -rf build/Release/suika.app && until xcodebuild -exportNotarizedApp -archivePath `pwd`/build/Release/suika.xcarchive -exportPath `pwd`/build/Release; do echo "Sleep..."; sleep 10; done
+	@echo "Creating dmg files..."
+	@rm -rf tmp mac.dmg && mkdir tmp && cp -Ra build/Release/suika.app tmp/ && hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname suika-mac mac.dmg && codesign --sign $(SIGNATURE) mac.dmg && rm -rf tmp
+
+#
+# Build release pro app
+#
+pro: libroot
+	@echo "Building..."
+	@security unlock-keychain -p "$(MACOS_PASSWORD)" login.keychain
 	@echo "Builing suika-pro.app" && xcodebuild -scheme suika-pro -project suika.xcodeproj -configuration Release -archivePath `pwd`/build/Release/suika-pro.xcarchive archive
 	@echo "Uploading suika-pro.app" && xcodebuild -exportArchive -archivePath `pwd`/build/Release/suika-pro.xcarchive -exportOptionsPlist export-options.plist
 	@echo "Notarizing suika-pro.app" && rm -rf build/Release/suika-pro.app && until xcodebuild -exportNotarizedApp -archivePath `pwd`/build/Release/suika-pro.xcarchive -exportPath `pwd`/build/Release; do echo "Sleep..."; sleep 10; done
 	@echo "Creating dmg files..."
-	@rm -rf tmp mac.dmg && mkdir tmp && cp -Ra build/Release/suika.app tmp/ && hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname suika-mac mac.dmg && codesign --sign $(SIGNATURE) mac.dmg && rm -rf tmp
 	@rm -rf tmp mac-pro.dmg && mkdir tmp && cp -Ra build/Release/suika-pro.app tmp/ && hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname suika-mac-pro mac-pro.dmg && codesign --sign $(SIGNATURE) mac-pro.dmg && rm -rf tmp
+
+#
+# Build release helpers
+#
+helpers:
 	@echo "Creating a zip file for use with Kirara..."
 	@rm -rf zip mac.zip && mkdir zip
 	@cp -Rv build/Release/suika.app zip/
@@ -68,16 +64,24 @@ release: libroot
 	@cd ../../tools/pack && make pack.mac && cp pack.mac ../../build/macos/ && cd ../../build/macos
 
 #
-# Build capture-and-replay apps
+# Build suika-capture.app
 #
-cap-rep: libroot
+capture: libroot
 	@if [ -z "$SSH_CLIENT" ]; then echo "Cannot run in an ssh session due to a codesign issue."; exit 1; fi
 	@echo "Building..."
-	@rm -rf build mac-capture.dmg mac-replay.dmg
+	@rm -rf build mac-capture.dmg
 	@echo "Builing suika-capture.app" && xcodebuild -scheme suika-capture -project suika.xcodeproj -configuration Release -archivePath `pwd`/build/Release/suika-capture.xcarchive archive
 	@echo "Uploading suika-capture.app" && xcodebuild -exportArchive -archivePath `pwd`/build/Release/suika-capture.xcarchive -exportOptionsPlist export-options.plist
 	@echo "Notarizing suika-capture.app" && rm -rf build/Release/suika-capture.app && until xcodebuild -exportNotarizedApp -archivePath `pwd`/build/Release/suika-capture.xcarchive -exportPath `pwd`/build/Release; do echo "Sleep..."; sleep 10; done
 	@echo "Creating suika-capture.dmg" && rm -rf tmp mac-capture.dmg && mkdir tmp && cp -Ra build/Release/suika-capture.app tmp/ && hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname suika-mac-capture mac-capture.dmg && codesign --sign $(SIGNATURE) mac-capture.dmg && rm -rf tmp
+
+#
+# Build suika-replay.app
+#
+replay: libroot
+	@if [ -z "$SSH_CLIENT" ]; then echo "Cannot run in an ssh session due to a codesign issue."; exit 1; fi
+	@echo "Building..."
+	@rm -rf build mac-replay.dmg
 	@echo "Builing suika-replay.app" && xcodebuild -scheme suika-replay -project suika.xcodeproj -configuration Release -archivePath `pwd`/build/Release/suika-replay.xcarchive archive
 	@echo "Uploading suika-replay.app" && xcodebuild -exportArchive -archivePath `pwd`/build/Release/suika-replay.xcarchive -exportOptionsPlist export-options.plist
 	@echo "Notarizing suika-replay.app" && rm -rf build/Release/suika-replay.app && until xcodebuild -exportNotarizedApp -archivePath `pwd`/build/Release/suika-replay.xcarchive -exportPath `pwd`/build/Release; do echo "Sleep..."; sleep 10; done
